### ISSUE TITLE
could you share the train example of json file format

### ISSUE THREAD

**Issue by xiaochen-liu** [jackd/template_ffd#1]
it  is very great project.  i want to run the train code . so could you give one example json file for training '/template_ffd/model/params/example.json'.

**Comment by AmyWan** [comment]
@xiaochen-liu could you tell me how to get the json,there were not floder in params

**Comment by jackd** [comment]
`eval/create_paper_params.py` will create a bunch of parameter files used in the paper - though the following should get you started (`e_plane.json` created with the above)

```
{
  "inference_params": {
    "alpha": 0.25
  },
  "entropy_loss": {
    "exp_annealing_rate": 0.0001,
    "weight": 100.0
  },
  "cat_desc": "plane",
  "use_bn_bugged_version": true
}
```

Note `use_bv_bugged_version` is for back-compatibility with paper models - if training from scratch there's no reason to keep it true.

Also, an updated version of the paper got accepted to ACCV, so I'm hoping to revisit this code in a couple of weeks to clean a few things up before the conference. Changes won't be back-compatible, but I'll fork before I intentionally break things.

**Comment by AmyWan** [comment]
@jackd hi.I cant find the eval/create_paper_params.py?and no .json file
hope to help me ,thank you
