### ISSUE TITLE
Question about implementation

### ISSUE THREAD

**Issue by saurabbhsp** [jackd/template_ffd#13]
I was going over the code and I had few questions.
1) Are the weights for mobile net trainable
2) get_mobilenet_features will initialize mobile net with imagenet weights once but what will happen when weights=None

**Comment by jackd** [comment]
1. Yes
2. After the initial run, weights are not initialized by keras. However, the `tf.estimator` framework automatically loads weights from the latest checkpoint in the `model_dir`. The manner in which it does this is very different to keras - they don't play nicely together, hence the different nature of calling. The first run loads weights 'the keras way' then immediately saves them the `estimator`/native tensorflow way.

It's a hideous, hideous hack, made worse by the unnecessary size checks in the keras source code (hence my copy-paste job with minimal changes), which got even worse when the keras implementation changed.

**Comment by saurabbhsp** [comment]
Yes. The keras updated implementation also messed up my codebase. I rolled back to version 2.1.1. 

Thanks for all the help.
