### ISSUE TITLE
Getting warnings in preprocessing

### ISSUE THREAD

**Issue by saurabbhsp** [jackd/template_ffd#6]
Hi,
While trying to execute
 ``` console
python render_cat.py plane
``` 
I am getting warnings. "Invalid clnors in this fan!". Should I ignore this warning? 
PS:- Images are still generated

**Comment by jackd** [comment]
Looks like an issue with blender and the original meshes (clnors is "custom loop normals"). It might result in a few small artefacts, so I guess you can chase it down if you want by preprocessing the meshes... but I've never bothered. See [this post](https://blender.stackexchange.com/questions/77332/invalid-clnors-in-this-fan-warning) for more.

**Comment by saurabbhsp** [comment]
Thanks!!
