### ISSUE TITLE
Question about mobilenet hack

### ISSUE THREAD

**Issue by saurabbhsp** [jackd/template_ffd#9]
Hi,
I was going over the code repository and found the hack for keras mobile net. If I understand correctly this hack is required because the resolution of images is 256X192 and imagenet weights are only trained for square images. I was thinking was there any reason for this resolution and not converting the images to 256X256 during preprocessing. This will avoid usage of mobile net hack.

Thanks for all the help.

**Comment by jackd** [comment]
I wanted results to be comparable to other approaches, which used 192 x 256 images - but that's purely a comparison thing. Your proposal should work fine, and be more elegant than mine in the absence of that comparison condition.

**Comment by saurabbhsp** [comment]
Thanks. That helps
